{
 "title": "Estação meteorológica",
 "time": { "from": "2023-06-11T23:52:06.000Z", "to": "2023-06-12T15:59:29.000Z" },
 "panels": [
  {
   "title": "Indice VOC agora",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"voc_index\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"uv\" )\n"
    }
   ]
  },
  {
   "title": "Pressão",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"pressure\")\n  |> keep(columns: [\"_time\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "Pressão agora",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"pressure\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Temperatura agora",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"hdc_temperature\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Humidade agora",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"hdc_humidity\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Lux",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"lux\" )\n"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"hdc_temperature\" )\n"
    }
   ]
  },
  {
   "title": "Humidade agora",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mW / cm 2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"uv\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Velocidade do vento",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mW*cm⁻2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"wind_speed\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Humidade",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"hdc_humidity\")\n"
    }
   ]
  },
  {
   "title": "SGP40 - VOC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "index" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"voc_index\")\n"
    }
   ]
  },
  {
   "title": "Velocidade do vento",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"wind_speed\")\n"
    }
   ]
  },
  {
   "title": "BME- VOC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"weather-station\")\n  |> filter(fn: (r) => r._field == \"gas_resistance\")\n"
    }
   ]
  }
 ]
}